import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nexttt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* NAVBAR */}
        {/* <div className="w-full h-20 bg-gray-100 py-5 px-10 flex justify-between">
          <a href="/">
            <h1 className="text-2xl">Home</h1>
          </a>

          <div className="flex gap-5 items-center">
            <a href="/about">About</a>
            <a href="/profile">Profile</a>
          </div>
        </div> */}
        
        {children}
      </body>
    </html>
  );
}
